"""Fixed one wrong symbol)

Revision ID: 0dbec348a8a2
Revises: f14e1c5f0c0d
Create Date: 2025-11-20 00:04:02.513771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbec348a8a2'
down_revision: Union[str, Sequence[str], None] = 'f14e1c5f0c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
