"""Fixed one wrong symbol)

Revision ID: f14e1c5f0c0d
Revises: e17ad2f10431
Create Date: 2025-11-20 00:03:45.768682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14e1c5f0c0d'
down_revision: Union[str, Sequence[str], None] = 'e17ad2f10431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
